version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
      - VITE_APP_NAME="Yo Me Uno - Donaciones Guatemala"
      - VITE_APP_VERSION=1.0.0
      - VITE_APP_DESCRIPTION="Plataforma de donaciones para organizaciones guatemaltecas"
      - VITE_NODE_ENV=production
      - VITE_ENABLE_ANALYTICS=false
      - VITE_ENABLE_ERROR_REPORTING=true
      - VITE_SUPPORT_EMAIL=soporte@yomeuno.gt
      - VITE_SUPPORT_PHONE=+502-1234-5678
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional, for development with hot reload)
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://host.docker.internal:8000/api/v1
      - VITE_APP_NAME="Yo Me Uno - Donaciones Guatemala (Dev)"
      - VITE_APP_VERSION=1.0.0-dev
      - VITE_NODE_ENV=development
    profiles:
      - dev
    command: pnpm dev --host 0.0.0.0