[build]
  command = "pnpm install --frozen-lockfile && pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "8"

# Environment variables for production
[context.production.environment]
  VITE_API_URL = "https://mgen-backend-production.up.railway.app/api/v1"
  VITE_API_TIMEOUT = "15000"
  VITE_APP_NAME = "Yo Me Uno - Donaciones Guatemala"
  VITE_APP_VERSION = "1.0.0"
  VITE_NODE_ENV = "production"
  VITE_ENABLE_ANALYTICS = "false"
  VITE_ENABLE_ERROR_REPORTING = "true"

# Add security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"


